### ISSUE TITLE
what is ./Config/Config,json?

### ISSUE THREAD

**Issue by Vishal1419** [paulomcnally/dustjs-helpers-moment#1]
I cannot find any file named Config,json in my nodejs project.

Can you please help me on this?

I also have some code before installing this package:

`<td class="col-orderDate">{.orderDate}</td>`

Now, I have converted it to something like this:

`<td class="col-orderDate">{@moment type="format" date=".orderDate" format="DD-MM-YYYY" /}</td>`

Is this correct?

**Comment by paulomcnally** [comment]
Hi.

config.json it's for KrakenJS projects.

I recomend https://github.com/krakenjs/adaro to use dustjs with expressJS.

**Comment by Vishal1419** [comment]
Thank you @paulomcnally
